unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <inlineHelpText>Source: Moldev (Industry), SCIEX (Industry), IDBS (Industry), Leica (Industry,Department,Sub Department,Division) &amp; Beckman (Industry)</inlineHelpText>
        <label>Industry</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Defense</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Apparel</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biosecurity</fullName>
                </value>
                <value>
                    <fullName>Biotechnology</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Contract Research Organizations</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverage</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Machinery</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Not For Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Undefined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Source: Moldev (Type), SCIEX (Type, Location Type, Customer Account Type), IDBS (Type), Leica (Corporate Account Type, Special Account Type, Account Type) &amp; Beckman (Type)</inlineHelpText>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Global HQ</fullName>
                    <label>MOL - Global HQ</label>
                </value>
                <value>
                    <fullName>Main HQ</fullName>
                    <label>MOL - Main HQ</label>
                </value>
                <value>
                    <fullName>International HQ</fullName>
                    <label>MOL - International HQ</label>
                </value>
                <value>
                    <fullName>Subsidiary</fullName>
                    <label>MOL - Subsidiary</label>
                </value>
                <value>
                    <fullName>MOL - Branch</fullName>
                </value>
                <value>
                    <fullName>University</fullName>
                    <label>MOL - University</label>
                </value>
                <value>
                    <fullName>US HQ</fullName>
                    <label>MOL - US HQ</label>
                </value>
                <value>
                    <fullName>Canada HQ</fullName>
                    <label>MOL - Canada HQ</label>
                </value>
                <value>
                    <fullName>UK HQ</fullName>
                    <label>MOL - UK HQ</label>
                </value>
                <value>
                    <fullName>France HQ</fullName>
                    <label>MOL - France HQ</label>
                </value>
                <value>
                    <fullName>Germany HQ</fullName>
                    <label>MOL - Germany HQ</label>
                </value>
                <value>
                    <fullName>Spain HQ</fullName>
                    <label>MOL - Spain HQ</label>
                </value>
                <value>
                    <fullName>Netherlands HQ</fullName>
                    <label>MOL - Netherlands HQ</label>
                </value>
                <value>
                    <fullName>Switzerland HQ</fullName>
                    <label>MOL - Switzerland HQ</label>
                </value>
                <value>
                    <fullName>Sweden HQ</fullName>
                    <label>MOL - Sweden HQ</label>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                    <label>MOL - Distributor</label>
                </value>
                <value>
                    <fullName>MOL - Single Location</fullName>
                </value>
                <value>
                    <fullName>MOL - Italy HQ</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <label>MOL - Agent</label>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                    <label>MOL - Reseller</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <label>MOL - Other</label>
                </value>
                <value>
                    <fullName>IDB - Competitor</fullName>
                </value>
                <value>
                    <fullName>IDB - Customer</fullName>
                </value>
                <value>
                    <fullName>IDB - Partner</fullName>
                </value>
                <value>
                    <fullName>IDB - Prospect</fullName>
                </value>
                <value>
                    <fullName>IDB - Reseller</fullName>
                </value>
                <value>
                    <fullName>IDB - Other</fullName>
                </value>
                <value>
                    <fullName>IDB - Site Closed</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                    <label>IDB - Lead</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                    <label>IDB - Delete</label>
                </value>
                <value>
                    <fullName>Undefined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/objects/Mapping_Master__c.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Object__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate_Account_Type__c</fullName>
                    <label>Corporate Account Type</label>
                </value>
                <value>
                    <fullName>Account_Type__c</fullName>
                    <label>Account Type</label>
                </value>
                <value>
                    <fullName>Special_Account_Type__c</fullName>
                    <label>Special Account Type</label>
                </value>
                <value>
                    <fullName>Market_Segment__c</fullName>
                    <label>Market Segment</label>
                </value>
                <value>
                    <fullName>Business_Division__c</fullName>
                    <label>Business Division</label>
                </value>
                <value>
                    <fullName>Division__c</fullName>
                    <label>Division</label>
                </value>
                <value>
                    <fullName>Department__c</fullName>
                    <label>Department</label>
                </value>
                <value>
                    <fullName>Sub_Department__c</fullName>
                    <label>Sub Department</label>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>Decision_Maker__c</fullName>
                    <label>Decision Maker</label>
                </value>
                <value>
                    <fullName>LeadSource</fullName>
                    <label>Lead Source</label>
                </value>
                <value>
                    <fullName>Inactive__c</fullName>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Application_of_Interest__c</fullName>
                    <label>Application of Interest</label>
                </value>
                <value>
                    <fullName>Area_of_Interest__c</fullName>
                    <label>Area of Interest</label>
                </value>
                <value>
                    <fullName>StageName</fullName>
                    <label>Stage</label>
                </value>
                <value>
                    <fullName>Contact Type</fullName>
                </value>
                <value>
                    <fullName>Primary_Application__c</fullName>
                    <label>Primary Application</label>
                </value>
                <value>
                    <fullName>Secondary_Application__c</fullName>
                    <label>Secondary Application</label>
                </value>
                <value>
                    <fullName>Market_Vertical1__c</fullName>
                    <label>Market Vertical 1</label>
                </value>
                <value>
                    <fullName>Market_Vertical_2__c</fullName>
                    <label>Market Vertical 2</label>
                </value>
                <value>
                    <fullName>Competitor_1__c</fullName>
                    <label>Competitor 1</label>
                </value>
                <value>
                    <fullName>Competitor_Product_1__c</fullName>
                    <label>Competitor Product 1</label>
                </value>
                <value>
                    <fullName>Competitor_2__c</fullName>
                    <label>Competitor 2</label>
                </value>
                <value>
                    <fullName>Competitor_Product_2__c</fullName>
                    <label>Competitor Product 2</label>
                </value>
                <value>
                    <fullName>Competitor_3__c</fullName>
                    <label>Competitor 3</label>
                </value>
                <value>
                    <fullName>Competitor_Product_3__c</fullName>
                    <label>Competitor Product 3</label>
                </value>
                <value>
                    <fullName>Location_Type__c</fullName>
                    <label>Location Type</label>
                </value>
                <value>
                    <fullName>Customer_account_type__c</fullName>
                    <label>Customer Account Type</label>
                </value>
                <value>
                    <fullName>Type</fullName>
                </value>
                <value>
                    <fullName>Institution_Type__c</fullName>
                    <label>Institution Type</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mapping Master</label>
    <nameField>
        <displayFormat>MMID-{00000}</displayFormat>
        <label>Mapping Master ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/OpCo_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OpCo Accounts Data</relationshipLabel>
        <relationshipName>OpCo_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OpCo Account Data</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>OpCo Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpCo Accounts Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Danaher_AccUpdate.cls
public class Danaher_AccUpdate {
 public static Void handler(List<OpCo_Account__c> lstOpAcc)
	{
    	 Set<id> accId = new set<id>();
         for(opCo_Account__c opco :lstOpAcc)   
        	{
           		 accId.add(opco.Account__c) ;
        	}
            /*Account Records */
          List<Account> lstAcc=new List<Account>([select id,name,Type__c,Industry__c from Account where id in :accId]);
           /* Records of Mapping Master for Account Object */
         List<Mapping_Master__c> mappingRec=[
            SELECT 
            ID,Object__c,Source_Field__c,Source_OpCo__c,
            Source_Value__c,Destination_Field__c,Destination_Value__c
            FROM Mapping_Master__c 
            WHERE Object__c='Account' and Destination_Field__c in ('Type_lsig__c')];
        Map<String,String> mapMasMap=new Map<String,String>();
        for(Mapping_Master__c val:mappingRec)
        {
            mapMasMap.put(val.Source_Value__c+val.Source_OpCo__c,val.Destination_Value__c);
        }
        /*Industry Picklist Values */
         List<String>typePickListValues=new List<String>();
        Schema.DescribeFieldResult typeFieldLabel = Account.Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = typeFieldLabel.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            typePickListValues.add(pickListVal.getLabel());            
        }
              	/* Main Code Start*/
         for(opCo_Account__c opCoAcc:lstOpAcc)
         {
			Set<String> tpye =new Set<String>();
            Set<String> industry =new Set<String>();
            // PickList String type value 
            String typePickVal=''; 
            // PickList String industry value
            String industryPickVal=''; 
            system.debug(opCoAcc);
            
            // Inner Loop for child records of specific account i.e PFizer as acc
            //   for(OpCo_Account__c opCoAcc:acc.OpCo_Accounts__r){
            List<String> Typevalue =new  List<String>();
            if(opCoAcc.Type__c!=NULL)
            {
                if(opCoAcc.Type__c.contains(','))
                {
                    Typevalue =opCoAcc.Type__c.split(',');
                }else{
                    Typevalue.add(opCoAcc.Type__c);
                }  
            }
            for(String str:Typevalue)
              {
                for(Mapping_Master__c mapRes:mappingRec)
                {
                    if(mapMasMap.containsKey(str+opCoAcc.Source__c))
                    {
                         String value=mapMasMap.get(str+opCoAcc.Source__c);
                         Integer ind=Typevalue.indexOf(str);
                        	if(ind!=-1)
                            {
                                Typevalue.set(ind, value);
                            }
                         
                    }
                }
              }
             
             /*Adding value to Set*/
             for(String str:Typevalue)
             {
                 tpye.add(str);
             }
             for(Account ac:lstAcc)
             {
                 if(ac.ID==opCoAcc.Account__c)
                 {
                     if(ac.Type__c!=NULL)
                     {
                         String value=ac.Type__c;
                         List<String> ls=value.split(';');
                         for(String str:ls)
                         {
                             Typevalue.add(str);
                         }
                         
                     }
                 }
             }
             for(String str:Typevalue)
             {
                 if(!typePickListValues.contains(str))
                    {
                        tpye.add('Undefined');
                    }  
                 else
                     {
                     tpye.add(str);
                     }

             }
             if(tpye.Size()>0)
             {
                 for(String str:tpye)
                 {
                   typePickVal+=str+';';
                 }
                 
             }
             if(typePickVal.length()>0)
             {
                 typePickVal=typePickVal.substring(0,typePickVal.length()-1);
             }
             for(Account ac:lstAcc)
             {
                 if(ac.ID==opCoAcc.Account__c)
                 {
                     ac.Type__c=typePickVal;
                 }
             }
             
	    }
        system.debug(lstAcc);
        update lstAcc;
   }
}