unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DUNS_Number__c</fullName>
        <externalId>true</externalId>
        <label>DUNS Number</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/objects/OpCo_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OpCo Accounts Data</relationshipLabel>
        <relationshipName>OpCo_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DUNS_Number__c</fullName>
        <label>DUNS Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipping_Country__c</fullName>
        <label>Shipping Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source OpCo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beckman</fullName>
                </value>
                <value>
                    <fullName>IDBS</fullName>
                </value>
                <value>
                    <fullName>Leica</fullName>
                </value>
                <value>
                    <fullName>Moldev</fullName>
                </value>
                <value>
                    <fullName>SCIEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit_Code__c</fullName>
        <label>Unit Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OpCo Account Data</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>OpCo Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpCo Accounts Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/OpCo_Account_trgHandler.cls
public class OpCo_Account_trgHandler {
    public static Void handler(List<OpCo_Account__c> lstAcc){
        List<Account>lstDUNS=[SELECT ID,ParentId,DUNS_Number__c FROM Account where DUNS_Number__c !=null];
        for(OpCo_Account__c ac:lstAcc){
            String XUNMATCHED='';
            String DONOTUSE='';
                       
            if(ac.Account__c!=null){
                List<Account>acc=[SELECT ID,Name FROM Account Where ParentId = :ac.Account__c AND (NAME Like '%XUNMATCHED%' OR NAME Like '%DO NOT USE%') ORDER BY Name];
                DONOTUSE=acc[0].ID;
                XUNMATCHED=acc[1].ID; 
            }
            // Country Mapping for Leica
            if(!(ac.Source__c=='Leica' && (ac.Shipping_Country__c.containsAny('United States')||
             ac.Shipping_Country__c.containsAny('United States America')||ac.Shipping_Country__c.containsAny('US')||
             ac.Shipping_Country__c.containsAny('USA')||ac.Shipping_Country__c.containsAny('Canada')||ac.Shipping_Country__c.containsAny('CA')||
             ac.Shipping_Country__c.containsAny('CAN')||ac.Billing_Country__c.containsAny('United States')||ac.Billing_Country__c.containsAny('United States America')||
             ac.Billing_Country__c.containsAny('US')||ac.Billing_Country__c.containsAny('USA')||ac.Billing_Country__c.containsAny('Canada')||ac.Billing_Country__c.containsAny('CA')||
             ac.Billing_Country__c.containsAny('CAN')||ac.Unit_Code__c.containsAny('Canada')))){
               
                 ac.Account__c=DONOTUSE;
                continue;
            }
            // Country Mapping other OpCo
            if(!(ac.Source__c!='Leica' && (ac.Shipping_Country__c.containsAny('United States')||ac.Shipping_Country__c.containsAny('United States America')||ac.Shipping_Country__c.containsAny('US')||ac.Shipping_Country__c.containsAny('USA')||ac.Shipping_Country__c.containsAny('Canada')||ac.Shipping_Country__c.containsAny('CA')||ac.Shipping_Country__c.containsAny('CAN')||ac.Billing_Country__c.containsAny('United States')||ac.Billing_Country__c.containsAny('United States America')||ac.Billing_Country__c.containsAny('US')||ac.Billing_Country__c.containsAny('USA')||ac.Billing_Country__c.containsAny('Canada')||ac.Billing_Country__c.containsAny('CA')||ac.Billing_Country__c.containsAny('CAN')))){
                ac.Account__c=DONOTUSE;
                continue;
            }
            // FOR DUNS 
            if(ac.DUNS_Number__c!=null){
                for(Account acc:lstDUNS){
                    if(acc.DUNS_Number__c.containsAny(ac.DUNS_Number__c)){
                        ac.Account__c=acc.ParentID;
                        continue;
                    }
                }
            }
            //
            
            
        }
    }
}