unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <inlineHelpText>Source: Moldev (Industry), SCIEX (Industry), IDBS (Industry), Leica (Industry,Department,Sub Department,Division) &amp; Beckman (Industry)</inlineHelpText>
        <label>Industry</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Defense</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Apparel</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biosecurity</fullName>
                </value>
                <value>
                    <fullName>Biotechnology</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Contract Research Organizations</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverage</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Machinery</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Not For Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Undefined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Source: Moldev (Type), SCIEX (Type, Location Type, Customer Account Type), IDBS (Type), Leica (Corporate Account Type, Special Account Type, Account Type) &amp; Beckman (Type)</inlineHelpText>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Global HQ</fullName>
                    <label>MOL - Global HQ</label>
                </value>
                <value>
                    <fullName>Main HQ</fullName>
                    <label>MOL - Main HQ</label>
                </value>
                <value>
                    <fullName>International HQ</fullName>
                    <label>MOL - International HQ</label>
                </value>
                <value>
                    <fullName>Subsidiary</fullName>
                    <label>MOL - Subsidiary</label>
                </value>
                <value>
                    <fullName>MOL - Branch</fullName>
                </value>
                <value>
                    <fullName>University</fullName>
                    <label>MOL - University</label>
                </value>
                <value>
                    <fullName>US HQ</fullName>
                    <label>MOL - US HQ</label>
                </value>
                <value>
                    <fullName>Canada HQ</fullName>
                    <label>MOL - Canada HQ</label>
                </value>
                <value>
                    <fullName>UK HQ</fullName>
                    <label>MOL - UK HQ</label>
                </value>
                <value>
                    <fullName>France HQ</fullName>
                    <label>MOL - France HQ</label>
                </value>
                <value>
                    <fullName>Germany HQ</fullName>
                    <label>MOL - Germany HQ</label>
                </value>
                <value>
                    <fullName>Spain HQ</fullName>
                    <label>MOL - Spain HQ</label>
                </value>
                <value>
                    <fullName>Netherlands HQ</fullName>
                    <label>MOL - Netherlands HQ</label>
                </value>
                <value>
                    <fullName>Switzerland HQ</fullName>
                    <label>MOL - Switzerland HQ</label>
                </value>
                <value>
                    <fullName>Sweden HQ</fullName>
                    <label>MOL - Sweden HQ</label>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                    <label>MOL - Distributor</label>
                </value>
                <value>
                    <fullName>MOL - Single Location</fullName>
                </value>
                <value>
                    <fullName>MOL - Italy HQ</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <label>MOL - Agent</label>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                    <label>MOL - Reseller</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <label>MOL - Other</label>
                </value>
                <value>
                    <fullName>IDB - Competitor</fullName>
                </value>
                <value>
                    <fullName>IDB - Customer</fullName>
                </value>
                <value>
                    <fullName>IDB - Partner</fullName>
                </value>
                <value>
                    <fullName>IDB - Prospect</fullName>
                </value>
                <value>
                    <fullName>IDB - Reseller</fullName>
                </value>
                <value>
                    <fullName>IDB - Other</fullName>
                </value>
                <value>
                    <fullName>IDB - Site Closed</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                    <label>IDB - Lead</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                    <label>IDB - Delete</label>
                </value>
                <value>
                    <fullName>Undefined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/objects/Mapping_Master__c.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Object__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate_Account_Type__c</fullName>
                    <label>Corporate Account Type</label>
                </value>
                <value>
                    <fullName>Account_Type__c</fullName>
                    <label>Account Type</label>
                </value>
                <value>
                    <fullName>Special_Account_Type__c</fullName>
                    <label>Special Account Type</label>
                </value>
                <value>
                    <fullName>Market_Segment__c</fullName>
                    <label>Market Segment</label>
                </value>
                <value>
                    <fullName>Business_Division__c</fullName>
                    <label>Business Division</label>
                </value>
                <value>
                    <fullName>Division__c</fullName>
                    <label>Division</label>
                </value>
                <value>
                    <fullName>Department__c</fullName>
                    <label>Department</label>
                </value>
                <value>
                    <fullName>Sub_Department__c</fullName>
                    <label>Sub Department</label>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>Decision_Maker__c</fullName>
                    <label>Decision Maker</label>
                </value>
                <value>
                    <fullName>LeadSource</fullName>
                    <label>Lead Source</label>
                </value>
                <value>
                    <fullName>Inactive__c</fullName>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Application_of_Interest__c</fullName>
                    <label>Application of Interest</label>
                </value>
                <value>
                    <fullName>Area_of_Interest__c</fullName>
                    <label>Area of Interest</label>
                </value>
                <value>
                    <fullName>StageName</fullName>
                    <label>Stage</label>
                </value>
                <value>
                    <fullName>Contact Type</fullName>
                </value>
                <value>
                    <fullName>Primary_Application__c</fullName>
                    <label>Primary Application</label>
                </value>
                <value>
                    <fullName>Secondary_Application__c</fullName>
                    <label>Secondary Application</label>
                </value>
                <value>
                    <fullName>Market_Vertical1__c</fullName>
                    <label>Market Vertical 1</label>
                </value>
                <value>
                    <fullName>Market_Vertical_2__c</fullName>
                    <label>Market Vertical 2</label>
                </value>
                <value>
                    <fullName>Competitor_1__c</fullName>
                    <label>Competitor 1</label>
                </value>
                <value>
                    <fullName>Competitor_Product_1__c</fullName>
                    <label>Competitor Product 1</label>
                </value>
                <value>
                    <fullName>Competitor_2__c</fullName>
                    <label>Competitor 2</label>
                </value>
                <value>
                    <fullName>Competitor_Product_2__c</fullName>
                    <label>Competitor Product 2</label>
                </value>
                <value>
                    <fullName>Competitor_3__c</fullName>
                    <label>Competitor 3</label>
                </value>
                <value>
                    <fullName>Competitor_Product_3__c</fullName>
                    <label>Competitor Product 3</label>
                </value>
                <value>
                    <fullName>Location_Type__c</fullName>
                    <label>Location Type</label>
                </value>
                <value>
                    <fullName>Customer_account_type__c</fullName>
                    <label>Customer Account Type</label>
                </value>
                <value>
                    <fullName>Type</fullName>
                </value>
                <value>
                    <fullName>Institution_Type__c</fullName>
                    <label>Institution Type</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mapping Master</label>
    <nameField>
        <displayFormat>MMID-{00000}</displayFormat>
        <label>Mapping Master ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/OpCo_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OpCo Accounts Data</relationshipLabel>
        <relationshipName>OpCo_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OpCo Account Data</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>OpCo Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpCo Accounts Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Danaher_AccUpdateBatchHandler.cls
public class Danaher_AccUpdateBatchHandler {
    
    public static Void accUpdateHandler(List<opCo_Account__c> lstOpCoAcc){
        
        Set<id> accId = new set<id>();
        for(opCo_Account__c opco :lstOpCoAcc)   
        {
            accId.add(opco.Account__c) ;
            
        }
        
        Map<Id,Account> MapAcc=new Map<Id,Account>([select id,name,Type__c,Industry__c from Account where id in :accId]);
        
        
        /* Records of Mapping Master for Account Object */
        List<Mapping_Master__c> mappingRec=[
            SELECT 
            ID,Object__c,Source_Field__c,Source_OpCo__c,
            Source_Value__c,Destination_Field__c,Destination_Value__c
            FROM Mapping_Master__c 
            WHERE Object__c='Account' and Destination_Field__c in ('Industry_lsig__c','Type_lsig__c')];
        
        List<String>industryPickListValues=new List<String>();
        Schema.DescribeFieldResult industryFieldLabel = Account.Industry__c.getDescribe();
        List<Schema.PicklistEntry> ple = industryFieldLabel.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            industryPickListValues.add(pickListVal.getLabel());            
        }  
        
        List<String>typePickListValues=new List<String>();
        Schema.DescribeFieldResult typeFieldLabel = Account.Type__c.getDescribe();
        List<Schema.PicklistEntry> typ = typeFieldLabel.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : typ){
            typePickListValues.add(pickListVal.getLabel());
        }   
        
        for(opCo_Account__c opCoAcc:lstOpCoAcc){
            Set<String> tpye =new Set<String>();
            Set<String> industry =new Set<String>();
            // PickList String type value 
            String typePickVal=''; 
            // PickList String industry value
            String industryPickVal=''; 
            system.debug(opCoAcc);
            
            // Inner Loop for child records of specific account i.e PFizer as acc
            //   for(OpCo_Account__c opCoAcc:acc.OpCo_Accounts__r){
            List<String> Typevalue =new  List<String>();
            if(opCoAcc.Type__c!=NULL)
            {
                
                if(opCoAcc.Type__c.contains(','))
                {
                    Typevalue =opCoAcc.Type__c.split(',');
                }else{
                    Typevalue.add(opCoAcc.Type__c);
                }
                
                
                Map<string,string> AllMapMasterType = new  Map<string,string>();
                
                
                for(Mapping_Master__c mas:mappingRec){                    
                    if(opCoAcc.Source__c==mas.Source_OpCo__c){
                        AllMapMasterType.put(mas.Source_Value__c,mas.Destination_Value__c);
                    }
                }
                for(string Tvalue:Typevalue){
                    if(AllMapMasterType.containsKey(Tvalue)){   
                        tpye.add(AllMapMasterType.get(Tvalue));
                    }else{
                        tpye.add(AllMapMasterType.get(Tvalue)); 
                    }
                    
                }
                
                for(string Dvalue:tpye){
                    
                    if(!typePickListValues.contains(Dvalue)){
                        tpye.remove(Dvalue);
                        tpye.add('Undefined');
                    }
                    
                }
                
            }                
            
            
            
            
            
            
            List<String> Industryvalue =new  List<String>();           
            if(opCoAcc.Industry__c!=NULL)
            {
                if(opCoAcc.Industry__c.contains(','))
                {
                    Industryvalue =opCoAcc.Industry__c.split(',');
                }else{
                    Industryvalue.add(opCoAcc.Industry__c);
                }
                
                
                Map<string,string> AllMapMasterIndustry = new  Map<string,string>();
                
                
                for(Mapping_Master__c mas:mappingRec){                    
                    if(opCoAcc.Source__c==mas.Source_OpCo__c){
                        AllMapMasterIndustry.put(mas.Source_Value__c,mas.Destination_Value__c);
                    }
                }
                for(string Ivalue:Industryvalue){
                    if(AllMapMasterIndustry.containsKey(Ivalue)){   
                        industry.add(AllMapMasterIndustry.get(Ivalue));
                    }else{
                        industry.add(AllMapMasterIndustry.get(Ivalue)); 
                    }
                    
                }
                
                for(string Ivalue:industry){
                    
                    if(!industryPickListValues.contains(Ivalue)){
                        industry.remove(Ivalue);
                        industry.add('Undefined');
                    }                    
                }
            }
            
            system.debug('last industry'+industry);
            // Loop will create String i.e Prospect;Value; for type field 
            if(tpye.size()>0){
                for(String str:tpye){
                    typePickVal+=str+';';
                }
            }
            // Loop will create String i.e Prospect;Value; for industry field 
            if(industry.size()>0){
                for(String str:industry){
                    industryPickVal+=str+';';
                }
            }
            // String ; remove from last index 
            system.debug(typePickVal);
            system.debug(industryPickVal);
            
            if(typePickVal.length()>0){
                typePickVal=typePickVal.substring(0,typePickVal.length()-1); 
                string OldType='';
                //Assigning Multi Select Value to Account Object Type__c field
                if(MapAcc.get(opCoAcc.Account__c).Type__c != null )
                {
                    OldType=MapAcc.get(opCoAcc.Account__c).Type__c;
                    OldType+=';'+typePickVal;   
                    List<string> newTypeValues= OldType.split(';');
                    set<string> uniqType =new set<string>();
                    for(string val : newTypeValues){
                        uniqType.add(val); 
                    }
                    string newtyepickval ='';
                    if(uniqType.size()>0){
                        
                        for(String str:uniqType){
                            
                            newtyepickval+=str+';';
                        }
                        
                        if(newtyepickval.length()>0){
                            
                            newtyepickval=newtyepickval.substring(0,newtyepickval.length()-1);
                            MapAcc.get(opCoAcc.Account__c).Type__c=newtyepickval;                            
                        }                        
                    } 
                    
                }else{
                    MapAcc.get(opCoAcc.Account__c).Type__c=typePickVal;
                }
            }
            
            if(industryPickVal.length()>0){
                industryPickVal=industryPickVal.substring(0,industryPickVal.length()-1); 
                string OldIndustry='';
                // Assigning Multi Select Value to Account Object Industry__c field 
                
                if(MapAcc.get(opCoAcc.Account__c).Industry__c != null )
                {
                    OldIndustry=MapAcc.get(opCoAcc.Account__c).Industry__c;
                    OldIndustry+=';'+industryPickVal;     
                    List<string> newIndustryValues= OldIndustry.split(';');
                    set<string> uniqIndustry =new set<string>();
                    for(string val : newIndustryValues){
                        uniqIndustry.add(val); 
                    }
                    string newIndustrypickval ='';
                    if(uniqIndustry.size()>0){
                        
                        for(String str:uniqIndustry){
                            
                            newIndustrypickval+=str+';';
                        }
                        
                        if(newIndustrypickval.length()>0){
                            newIndustrypickval=newIndustrypickval.substring(0,newIndustrypickval.length()-1);
                            MapAcc.get(opCoAcc.Account__c).Type__c=newIndustrypickval;
                        } 
                        
                    } 
                    
                }else{
                    
                    MapAcc.get(opCoAcc.Account__c).Industry__c=industryPickVal;
                }
            }                   
            
        }
        system.debug(MapAcc.values());
        Database.update(MapAcc.values(),false);        
    }
}