unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Source: Moldev (Type), SCIEX (Type, Location Type, Customer Account Type), IDBS (Type), Leica (Corporate Account Type, Special Account Type, Account Type) &amp; Beckman (Type)</inlineHelpText>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Global HQ</fullName>
                    <label>MOL - Global HQ</label>
                </value>
                <value>
                    <fullName>Main HQ</fullName>
                    <label>MOL - Main HQ</label>
                </value>
                <value>
                    <fullName>International HQ</fullName>
                    <label>MOL - International HQ</label>
                </value>
                <value>
                    <fullName>Subsidiary</fullName>
                    <label>MOL - Subsidiary</label>
                </value>
                <value>
                    <fullName>MOL - Branch</fullName>
                </value>
                <value>
                    <fullName>University</fullName>
                    <label>MOL - University</label>
                </value>
                <value>
                    <fullName>US HQ</fullName>
                    <label>MOL - US HQ</label>
                </value>
                <value>
                    <fullName>Canada HQ</fullName>
                    <label>MOL - Canada HQ</label>
                </value>
                <value>
                    <fullName>UK HQ</fullName>
                    <label>MOL - UK HQ</label>
                </value>
                <value>
                    <fullName>France HQ</fullName>
                    <label>MOL - France HQ</label>
                </value>
                <value>
                    <fullName>Germany HQ</fullName>
                    <label>MOL - Germany HQ</label>
                </value>
                <value>
                    <fullName>Spain HQ</fullName>
                    <label>MOL - Spain HQ</label>
                </value>
                <value>
                    <fullName>Netherlands HQ</fullName>
                    <label>MOL - Netherlands HQ</label>
                </value>
                <value>
                    <fullName>Switzerland HQ</fullName>
                    <label>MOL - Switzerland HQ</label>
                </value>
                <value>
                    <fullName>Sweden HQ</fullName>
                    <label>MOL - Sweden HQ</label>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                    <label>MOL - Distributor</label>
                </value>
                <value>
                    <fullName>MOL - Single Location</fullName>
                </value>
                <value>
                    <fullName>MOL - Italy HQ</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <label>MOL - Agent</label>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                    <label>MOL - Reseller</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <label>MOL - Other</label>
                </value>
                <value>
                    <fullName>IDB - Competitor</fullName>
                </value>
                <value>
                    <fullName>IDB - Customer</fullName>
                </value>
                <value>
                    <fullName>IDB - Partner</fullName>
                </value>
                <value>
                    <fullName>IDB - Prospect</fullName>
                </value>
                <value>
                    <fullName>IDB - Reseller</fullName>
                </value>
                <value>
                    <fullName>IDB - Other</fullName>
                </value>
                <value>
                    <fullName>IDB - Site Closed</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                    <label>IDB - Lead</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                    <label>IDB - Delete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/objects/Mapping_Master__c.object
<CustomObject>
    <fields>
        <fullName>Destination_Field__c</fullName>
        <label>Destination Field</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Object__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type_lsig__c</fullName>
                    <label>Type Lsig</label>
                </value>
                <value>
                    <fullName>Market_Segment__c</fullName>
                    <label>Market Segment</label>
                </value>
                <value>
                    <fullName>Industry_lsig__c</fullName>
                    <label>Industry</label>
                </value>
                <value>
                    <fullName>Contact_Role__c</fullName>
                    <label>Contact Role</label>
                </value>
                <value>
                    <fullName>Status__c</fullName>
                    <label>Status</label>
                </value>
                <value>
                    <fullName>Application_Interest_Segment__c</fullName>
                    <label>Application Interest Segment</label>
                </value>
                <value>
                    <fullName>Sub_Application_Interest_Segment__c</fullName>
                    <label>Sub Application Interest Segment</label>
                </value>
                <value>
                    <fullName>Marketing_Vertical__c</fullName>
                    <label>Marketing Vertical</label>
                </value>
                <value>
                    <fullName>Product_Family__c</fullName>
                    <label>Product Family</label>
                </value>
                <value>
                    <fullName>StageName</fullName>
                    <label>Stage</label>
                </value>
                <value>
                    <fullName>Type</fullName>
                </value>
                <value>
                    <fullName>Line_of_Business__c</fullName>
                    <label>Line of Business</label>
                </value>
                <value>
                    <fullName>Competitor_Data__c</fullName>
                    <label>Competitor Data</label>
                </value>
                <value>
                    <fullName>Cancellation_Lost_Data__c</fullName>
                    <label>Cancellation/Lost Data</label>
                </value>
                <value>
                    <fullName>Product_Interest__c</fullName>
                    <label>Product Interest</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Destination_Value__c</fullName>
        <label>Destination Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Object__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate_Account_Type__c</fullName>
                    <label>Corporate Account Type</label>
                </value>
                <value>
                    <fullName>Account_Type__c</fullName>
                    <label>Account Type</label>
                </value>
                <value>
                    <fullName>Special_Account_Type__c</fullName>
                    <label>Special Account Type</label>
                </value>
                <value>
                    <fullName>Market_Segment__c</fullName>
                    <label>Market Segment</label>
                </value>
                <value>
                    <fullName>Business_Division__c</fullName>
                    <label>Business Division</label>
                </value>
                <value>
                    <fullName>Division__c</fullName>
                    <label>Division</label>
                </value>
                <value>
                    <fullName>Department__c</fullName>
                    <label>Department</label>
                </value>
                <value>
                    <fullName>Sub_Department__c</fullName>
                    <label>Sub Department</label>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>Decision_Maker__c</fullName>
                    <label>Decision Maker</label>
                </value>
                <value>
                    <fullName>LeadSource</fullName>
                    <label>Lead Source</label>
                </value>
                <value>
                    <fullName>Inactive__c</fullName>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Application_of_Interest__c</fullName>
                    <label>Application of Interest</label>
                </value>
                <value>
                    <fullName>Area_of_Interest__c</fullName>
                    <label>Area of Interest</label>
                </value>
                <value>
                    <fullName>StageName</fullName>
                    <label>Stage</label>
                </value>
                <value>
                    <fullName>Contact Type</fullName>
                </value>
                <value>
                    <fullName>Primary_Application__c</fullName>
                    <label>Primary Application</label>
                </value>
                <value>
                    <fullName>Secondary_Application__c</fullName>
                    <label>Secondary Application</label>
                </value>
                <value>
                    <fullName>Market_Vertical1__c</fullName>
                    <label>Market Vertical 1</label>
                </value>
                <value>
                    <fullName>Market_Vertical_2__c</fullName>
                    <label>Market Vertical 2</label>
                </value>
                <value>
                    <fullName>Competitor_1__c</fullName>
                    <label>Competitor 1</label>
                </value>
                <value>
                    <fullName>Competitor_Product_1__c</fullName>
                    <label>Competitor Product 1</label>
                </value>
                <value>
                    <fullName>Competitor_2__c</fullName>
                    <label>Competitor 2</label>
                </value>
                <value>
                    <fullName>Competitor_Product_2__c</fullName>
                    <label>Competitor Product 2</label>
                </value>
                <value>
                    <fullName>Competitor_3__c</fullName>
                    <label>Competitor 3</label>
                </value>
                <value>
                    <fullName>Competitor_Product_3__c</fullName>
                    <label>Competitor Product 3</label>
                </value>
                <value>
                    <fullName>Location_Type__c</fullName>
                    <label>Location Type</label>
                </value>
                <value>
                    <fullName>Customer_account_type__c</fullName>
                    <label>Customer Account Type</label>
                </value>
                <value>
                    <fullName>Type</fullName>
                </value>
                <value>
                    <fullName>Institution_Type__c</fullName>
                    <label>Institution Type</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_OpCo__c</fullName>
        <label>Source OpCo</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beckman</fullName>
                </value>
                <value>
                    <fullName>IDBS</fullName>
                </value>
                <value>
                    <fullName>Leica</fullName>
                </value>
                <value>
                    <fullName>Moldev</fullName>
                </value>
                <value>
                    <fullName>SCIEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Value__c</fullName>
        <label>Source Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Master</label>
    <nameField>
        <displayFormat>MMID-{00000}</displayFormat>
        <label>Mapping Master ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/OpCo_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OpCo Accounts Data</relationshipLabel>
        <relationshipName>OpCo_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OpCo Account Data</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>OpCo Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpCo Accounts Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>OpCo_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OpCo Account</label>
        <referenceTo>OpCo_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpCo_Stage__c</fullName>
        <label>OpCo Stage</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>IDBS</fullName>
        <active>true</active>
        <businessProcess>LSIG to OpCos Oppty</businessProcess>
        <description>IDBS Opportunities (Source &amp; LSIG)</description>
        <label>IDBS</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/OpCoAccountFieldUpdate_TrgTest.cls
@isTest
public class OpCoAccountFieldUpdate_TrgTest {
    @isTest
    public static void OpCoAccountFieldUpdate_Trg(){
        Account acc= new Account();
        acc.name = 'test';
        insert acc;
        
        date mydate = date.parse('12/27/2023');


        Opportunity oppdata = new Opportunity();
        oppdata.AccountId = acc.id;
        oppdata.Name = 'test1';
        oppdata.StageName = 'Qualification';
        oppdata.CloseDate = mydate;
        oppdata.OpCo_Stage__c='Type';
        insert oppdata;
        
        
        
        Mapping_Master__c mapMasterData = new Mapping_Master__c();
        mapMasterData.Object__c = 'Opportunity';
        mapMasterData.Source_Field__c = 'Type';
        mapMasterData.Source_OpCo__c = 'IDBS';
        mapMasterData.Source_Value__c='Type';
        mapMasterData.Destination_Value__c='Destination Value';
        mapMasterData.Destination_Field__c = 'Type';
        insert mapMasterData;
        
        OpCo_Account__c OpCo = new OpCo_Account__c();
        OpCo.Account__c = acc.Id;
        OpCo.Type__c = 'Type';
        OpCo.Source__c= 'IDBS';
        OpCo.Industry__c= 'Industry';
        insert OpCO;
        
       /* ID,Object__c,Source_Field__c,Source_OpCo__c,
     Source_Value__c,Destination_Field__c,Destination_Value__c */
            
        
            }
    
}