unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Industry__c</fullName>
        <inlineHelpText>Source: Moldev (Industry), SCIEX (Industry), IDBS (Industry), Leica (Industry,Department,Sub Department,Division) &amp; Beckman (Industry)</inlineHelpText>
        <label>Industry</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Academic</fullName>
                </value>
                <value>
                    <fullName>Aerospace &amp; Defense</fullName>
                </value>
                <value>
                    <fullName>Agriculture</fullName>
                </value>
                <value>
                    <fullName>Apparel</fullName>
                </value>
                <value>
                    <fullName>Banking</fullName>
                </value>
                <value>
                    <fullName>Biosecurity</fullName>
                </value>
                <value>
                    <fullName>Biotechnology</fullName>
                </value>
                <value>
                    <fullName>Chemicals</fullName>
                </value>
                <value>
                    <fullName>Communications</fullName>
                </value>
                <value>
                    <fullName>Construction</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Contract Research Organizations</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Energy</fullName>
                </value>
                <value>
                    <fullName>Engineering</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>Environmental</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>Food &amp; Beverage</fullName>
                </value>
                <value>
                    <fullName>Government</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>Hospitality</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Machinery</fullName>
                </value>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Not For Profit</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Source: Moldev (Type), SCIEX (Type, Location Type, Customer Account Type), IDBS (Type), Leica (Corporate Account Type, Special Account Type, Account Type) &amp; Beckman (Type)</inlineHelpText>
        <label>Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Global HQ</fullName>
                    <label>MOL - Global HQ</label>
                </value>
                <value>
                    <fullName>Main HQ</fullName>
                    <label>MOL - Main HQ</label>
                </value>
                <value>
                    <fullName>International HQ</fullName>
                    <label>MOL - International HQ</label>
                </value>
                <value>
                    <fullName>Subsidiary</fullName>
                    <label>MOL - Subsidiary</label>
                </value>
                <value>
                    <fullName>MOL - Branch</fullName>
                </value>
                <value>
                    <fullName>University</fullName>
                    <label>MOL - University</label>
                </value>
                <value>
                    <fullName>US HQ</fullName>
                    <label>MOL - US HQ</label>
                </value>
                <value>
                    <fullName>Canada HQ</fullName>
                    <label>MOL - Canada HQ</label>
                </value>
                <value>
                    <fullName>UK HQ</fullName>
                    <label>MOL - UK HQ</label>
                </value>
                <value>
                    <fullName>France HQ</fullName>
                    <label>MOL - France HQ</label>
                </value>
                <value>
                    <fullName>Germany HQ</fullName>
                    <label>MOL - Germany HQ</label>
                </value>
                <value>
                    <fullName>Spain HQ</fullName>
                    <label>MOL - Spain HQ</label>
                </value>
                <value>
                    <fullName>Netherlands HQ</fullName>
                    <label>MOL - Netherlands HQ</label>
                </value>
                <value>
                    <fullName>Switzerland HQ</fullName>
                    <label>MOL - Switzerland HQ</label>
                </value>
                <value>
                    <fullName>Sweden HQ</fullName>
                    <label>MOL - Sweden HQ</label>
                </value>
                <value>
                    <fullName>Distributor</fullName>
                    <label>MOL - Distributor</label>
                </value>
                <value>
                    <fullName>MOL - Single Location</fullName>
                </value>
                <value>
                    <fullName>MOL - Italy HQ</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                    <label>MOL - Agent</label>
                </value>
                <value>
                    <fullName>Reseller</fullName>
                    <label>MOL - Reseller</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <label>MOL - Other</label>
                </value>
                <value>
                    <fullName>IDB - Competitor</fullName>
                </value>
                <value>
                    <fullName>IDB - Customer</fullName>
                </value>
                <value>
                    <fullName>IDB - Partner</fullName>
                </value>
                <value>
                    <fullName>IDB - Prospect</fullName>
                </value>
                <value>
                    <fullName>IDB - Reseller</fullName>
                </value>
                <value>
                    <fullName>IDB - Other</fullName>
                </value>
                <value>
                    <fullName>IDB - Site Closed</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                    <label>IDB - Lead</label>
                </value>
                <value>
                    <fullName>Delete</fullName>
                    <label>IDB - Delete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/objects/OpCo_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OpCo Accounts Data</relationshipLabel>
        <relationshipName>OpCo_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <label>Industry</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source OpCo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beckman</fullName>
                </value>
                <value>
                    <fullName>IDBS</fullName>
                </value>
                <value>
                    <fullName>Leica</fullName>
                </value>
                <value>
                    <fullName>Moldev</fullName>
                </value>
                <value>
                    <fullName>SCIEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OpCo Account Data</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>OpCo Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpCo Accounts Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/Danaher_AccountTypeUpdateBatch.cls
/*
* @Developer-Sudhir Dhawan
* @Company-Nanostuffs Technologies Private Limited
* @Description-
* @TestClass - Danaher_ContactCreationBatchTest
*/
global class Danaher_AccountTypeUpdateBatch implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        //Query to get Records
        system.debug('@@@Start');
        
        
        return Database.getQueryLocator([
            SELECT ID,Type__c,Industry__c,Source__c,Account__c  FROM opCo_Account__c where Account__c !=NULL
        ]);
    }
    
    //
    global Void execute (Database.BatchableContext BC, List<opCo_Account__c> lstOPCoAcc){
        // Method to update the Account with Industry__c,Type__c Field
        system.debug(lstOPCoAcc); 
        Danaher_AccUpdateBatchHandler.accUpdateHandler(lstOPCoAcc);
        
    }
    //
    global void finish(Database.BatchableContext BC){
        
    }
    
}