unpackaged/objects/BaseURL__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This setting will be used for a formula field to generate the Source OpCo record link</description>
    <fields>
        <fullName>ContactBatchLimit__c</fullName>
        <label>ContactBatchLimitField</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OpCo Base URL</label>
</CustomObject>

unpackaged/objects/OpCo_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OpCo Accounts Data</relationshipLabel>
        <relationshipName>OpCo_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OpCo_Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OpCo Related Contact</label>
        <referenceTo>OpCo_Related_Contact__c</referenceTo>
        <relationshipLabel>OpCo Accounts Data</relationshipLabel>
        <relationshipName>OpCo_Accounts_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OpCo Account Data</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>OpCo Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpCo Accounts Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/OpCo_Related_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OpCo_LastModifiedDate__c</fullName>
        <label>OpCo Last Modified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Source_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source OpCo Account</label>
        <referenceTo>OpCo_Account__c</referenceTo>
        <relationshipLabel>OpCo Related Contacts</relationshipLabel>
        <relationshipName>OpCo_Related_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OpCo Related Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpCo Related Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Sync__c.object
<CustomObject>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Records_Checked__c</fullName>
        <label>Records Checked</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_Inserted__c</fullName>
        <label>Records Inserted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Records_Updated__c</fullName>
        <label>Records Updated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Script_Name__c</fullName>
        <label>Script Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Sync Jobs</label>
    <nameField>
        <displayFormat>SNID-{00000}</displayFormat>
        <label>Sync Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sync Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/Danaher_ContactCreationBatch.cls
/*
* @Developer-Sudhir Dhawan
* @Company-Nanostuffs Technologies Private Limited
* @Description-
* @TestClass-Danaher_ContactCreationBatchTest
*/
global class Danaher_ContactCreationBatch implements Database.Batchable<sObject>,Database.Stateful{
    global static List<Database.upsertResult> result=new List<Database.upsertResult>();
    global Database.QueryLocator start(Database.BatchableContext BC){
        //Query to get Records
        String lmt = BaseURL__c.getOrgDefaults().ContactBatchLimit__c;
        
        String qry='SELECT ID,Name,Email__c,Source_Account__r.Account__c FROM OpCo_Related_Contact__c Where Email__c !=\' \'  Order by OpCo_LastModifiedDate__c DESC ' +lmt+'';
        return Database.getQueryLocator(qry);
    }
    
    global void execute(Database.BatchableContext BC, List<OpCo_Related_Contact__c> lstOpRelContact){
        system.debug('@@@@');
        System.debug('lstOpRelContact:::'+lstOpRelContact);
        Danaher_ContactCreationBatch.result=Danaher_UniqueContactCreation.ContactCreation(lstOpRelContact);        
        
    }
    global void finish(Database.BatchableContext BC){
        Database.executeBatch(new Danaher_LSIGContactBatch(),100);
        Integer updated=0;
        Integer inserted=0;
        Integer checked=0;
        
        if(Danaher_ContactCreationBatch.result.Size()>0){
            system.debug('Danaher_ContactCreationBatch.result:::'+Danaher_ContactCreationBatch.result);
            for(Integer index = 0, size = Danaher_ContactCreationBatch.result.size(); index < size; index++) {
                if(Danaher_ContactCreationBatch.result[index].isSuccess()) {
                    checked++; 
                    if(Danaher_ContactCreationBatch.result[index].isCreated()) {
                        inserted++;
                    } else {
                        updated++;
                    }
                }
            }
            Sync__c syncObj=new Sync__c();
            syncObj.Object__c='Contact';
            syncObj.Records_Checked__c=checked;
            syncObj.Records_Inserted__c=inserted;
            syncObj.Records_Updated__c=updated;
            syncObj.Script_Name__c='Danaher_ContactCreationBatch';
            insert syncObj;
            //Batch to update LSIG Contact Field on OpCo Related Contact
            
        }
    }
}