unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OpCo_Contact_ID__c</fullName>
        <label>OpCo Contact ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/OpCo_Related_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LSIG_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LSIG Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>OpCo Related Contacts</relationshipLabel>
        <relationshipName>OpCo_Related_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OpCo Related Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpCo Related Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/Danaher_LSIGContactBatch.cls
/*
* @Developer-Sudhir Dhawan
* @Company-Nanostuffs Technologies Pvt Limited
* @Description- This batch class is used to update LSIG Contact Field on OpCoRelated Contact Object.The batch takes  all the 
* record from Contact Object.
* Then after iteration it compare with all related contacts email and finding the same email it update the contact ID.
*/

global class Danaher_LSIGContactBatch implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([ SELECT
                                         ID,LSIG_Contact__c,Email__c 
                                         FROM OpCo_Related_Contact__c
                                         Where Email__c!=''  ]);
        
    }
    global void execute(Database.BatchableContext BC, List<OpCo_Related_Contact__c> conLst){
        Set<String> setEmail=new Set<String>();
        for(OpCo_Related_Contact__c con:conLst){
            setEmail.add(con.Email__c);
        }
        
        // All OpCo Related Contacts 
        List<Contact> allConLst=[
            SELECT
            ID,OpCo_Contact_ID__c,Email
            FROM Contact 
            Where Email IN :setEmail ];
        // List of OpCoRelated Records that are to be updated 
        List<OpCo_Related_Contact__c> updateList=new List<OpCo_Related_Contact__c>();
        
        if(allConLst.Size()>0){
            for(OpCo_Related_Contact__c c:conLst){
                
                for(Contact opCon:allConLst){
                    if(c.Email__c==opCon.Email){
                        c.LSIG_Contact__c=opCon.ID;
                        updateList.add(c);
                    }
                }      
            }
        }
        system.debug(updateList);
        if(updateList.Size()>0){
            Database.update(updateList,false);
        }        
        
    }
    global void finish(Database.BatchableContext BC){
    }
    
}