unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Product_Family__c</fullName>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Mapping_Master__c.object
<CustomObject>
    <fields>
        <fullName>Destination_Field__c</fullName>
        <label>Destination Field</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Object__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Type_lsig__c</fullName>
                    <label>Type Lsig</label>
                </value>
                <value>
                    <fullName>Market_Segment__c</fullName>
                    <label>Market Segment</label>
                </value>
                <value>
                    <fullName>Industry_lsig__c</fullName>
                    <label>Industry</label>
                </value>
                <value>
                    <fullName>Contact_Role__c</fullName>
                    <label>Contact Role</label>
                </value>
                <value>
                    <fullName>Status__c</fullName>
                    <label>Status</label>
                </value>
                <value>
                    <fullName>Application_Interest_Segment__c</fullName>
                    <label>Application Interest Segment</label>
                </value>
                <value>
                    <fullName>Sub_Application_Interest_Segment__c</fullName>
                    <label>Sub Application Interest Segment</label>
                </value>
                <value>
                    <fullName>Marketing_Vertical__c</fullName>
                    <label>Marketing Vertical</label>
                </value>
                <value>
                    <fullName>Product_Family__c</fullName>
                    <label>Product Family</label>
                </value>
                <value>
                    <fullName>StageName</fullName>
                    <label>Stage</label>
                </value>
                <value>
                    <fullName>Type</fullName>
                </value>
                <value>
                    <fullName>Line_of_Business__c</fullName>
                    <label>Line of Business</label>
                </value>
                <value>
                    <fullName>Competitor_Data__c</fullName>
                    <label>Competitor Data</label>
                </value>
                <value>
                    <fullName>Cancellation_Lost_Data__c</fullName>
                    <label>Cancellation/Lost Data</label>
                </value>
                <value>
                    <fullName>Product_Interest__c</fullName>
                    <label>Product Interest</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Destination_Value__c</fullName>
        <label>Destination Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Field__c</fullName>
        <label>Source Field</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Object__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corporate_Account_Type__c</fullName>
                    <label>Corporate Account Type</label>
                </value>
                <value>
                    <fullName>Account_Type__c</fullName>
                    <label>Account Type</label>
                </value>
                <value>
                    <fullName>Special_Account_Type__c</fullName>
                    <label>Special Account Type</label>
                </value>
                <value>
                    <fullName>Market_Segment__c</fullName>
                    <label>Market Segment</label>
                </value>
                <value>
                    <fullName>Business_Division__c</fullName>
                    <label>Business Division</label>
                </value>
                <value>
                    <fullName>Division__c</fullName>
                    <label>Division</label>
                </value>
                <value>
                    <fullName>Department__c</fullName>
                    <label>Department</label>
                </value>
                <value>
                    <fullName>Sub_Department__c</fullName>
                    <label>Sub Department</label>
                </value>
                <value>
                    <fullName>Industry</fullName>
                </value>
                <value>
                    <fullName>Decision_Maker__c</fullName>
                    <label>Decision Maker</label>
                </value>
                <value>
                    <fullName>LeadSource</fullName>
                    <label>Lead Source</label>
                </value>
                <value>
                    <fullName>Inactive__c</fullName>
                    <label>Inactive</label>
                </value>
                <value>
                    <fullName>Application_of_Interest__c</fullName>
                    <label>Application of Interest</label>
                </value>
                <value>
                    <fullName>Area_of_Interest__c</fullName>
                    <label>Area of Interest</label>
                </value>
                <value>
                    <fullName>StageName</fullName>
                    <label>Stage</label>
                </value>
                <value>
                    <fullName>Contact Type</fullName>
                </value>
                <value>
                    <fullName>Primary_Application__c</fullName>
                    <label>Primary Application</label>
                </value>
                <value>
                    <fullName>Secondary_Application__c</fullName>
                    <label>Secondary Application</label>
                </value>
                <value>
                    <fullName>Market_Vertical1__c</fullName>
                    <label>Market Vertical 1</label>
                </value>
                <value>
                    <fullName>Market_Vertical_2__c</fullName>
                    <label>Market Vertical 2</label>
                </value>
                <value>
                    <fullName>Competitor_1__c</fullName>
                    <label>Competitor 1</label>
                </value>
                <value>
                    <fullName>Competitor_Product_1__c</fullName>
                    <label>Competitor Product 1</label>
                </value>
                <value>
                    <fullName>Competitor_2__c</fullName>
                    <label>Competitor 2</label>
                </value>
                <value>
                    <fullName>Competitor_Product_2__c</fullName>
                    <label>Competitor Product 2</label>
                </value>
                <value>
                    <fullName>Competitor_3__c</fullName>
                    <label>Competitor 3</label>
                </value>
                <value>
                    <fullName>Competitor_Product_3__c</fullName>
                    <label>Competitor Product 3</label>
                </value>
                <value>
                    <fullName>Location_Type__c</fullName>
                    <label>Location Type</label>
                </value>
                <value>
                    <fullName>Customer_account_type__c</fullName>
                    <label>Customer Account Type</label>
                </value>
                <value>
                    <fullName>Type</fullName>
                </value>
                <value>
                    <fullName>Institution_Type__c</fullName>
                    <label>Institution Type</label>
                </value>
                <value>
                    <fullName>Line_of_Business__c</fullName>
                    <label>Line of Business</label>
                </value>
                <value>
                    <fullName>Product_Family__c</fullName>
                    <label>Product Family</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_OpCo__c</fullName>
        <label>Source OpCo</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beckman</fullName>
                </value>
                <value>
                    <fullName>IDBS</fullName>
                </value>
                <value>
                    <fullName>Leica</fullName>
                </value>
                <value>
                    <fullName>Moldev</fullName>
                </value>
                <value>
                    <fullName>SCIEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source_Value__c</fullName>
        <label>Source Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mapping Master</label>
    <nameField>
        <displayFormat>MMID-{00000}</displayFormat>
        <label>Mapping Master ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/OpCo_Related_Contact__c.object
<CustomObject>
    <fields>
        <fullName>LSIG_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LSIG Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>OpCo Related Contacts</relationshipLabel>
        <relationshipName>OpCo_Related_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_OpCo_Record_Id__c</fullName>
        <externalId>true</externalId>
        <label>Source OpCo Record Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>OpCo Related Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpCo Related Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Cancellation_Lost_Data__c</fullName>
        <label>Won Lost Reason</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Role_ID__c</fullName>
        <label>Contact Role ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LSIG_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LSIG Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpCo_Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OpCo Related Contact</label>
        <referenceTo>OpCo_Related_Contact__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Family__c</fullName>
        <inlineHelpText>Source: Moldev (Product Family) SCIEX (Primary Application) IDBS (Primary Products) Leica (Primary Application, Secondary Application) &amp; Beckman (Product Type, Product Line, Additional Details, Product Groups, Product Moldes, Product Interest, Application Interest, Desired Product, Application)</inlineHelpText>
        <label>Product Family</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_OpCo_Record_Id__c</fullName>
        <externalId>true</externalId>
        <label>Source OpCo Record Id</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/OppTrgHandler.cls
public class OppTrgHandler {
	public static Void updateTrigger (List<Opportunity> lstOpp)
    {
        /* Find all Lsig opCo RElated Contact IDS  For all contact roles in this trigger */
        Set<String>IDs=new Set<String>();
        for(Opportunity op:lstOpp)
        {
            IDs.add(op.Contact_Role_ID__c);    
        }
        
        List<opCo_Related_Contact__c> lstRelContacts=[SELECT ID,LSIG_Contact__c FROM opCO_Related_Contact__c Where Source_OpCo_Record_Id__c IN :IDs];
        
         /* Mapping Master Records where object is contact */
        List<Mapping_Master__c> mappingRec=[
            SELECT 
            ID,Object__c,Source_Field__c,Source_OpCo__c,
            Source_Value__c,Destination_Field__c,Destination_Value__c
            FROM Mapping_Master__c 
            WHERE Object__c='Opportunity'];
        
       							 /*Product Family */
        List<Mapping_Master__c> prodFamily=[
            SELECT ID,Destination_Value__c, Source_OpCo__c,Destination_Field__c,Object__c 
            From Mapping_Master__c
            Where Destination_Field__c ='Product_Family__c' and Object__c ='Opportunity'
        ];
        Map<String,String> prodFamilyMap=new Map<String,String>();
        for(Mapping_Master__c val:prodFamily)
        {
            prodFamilyMap.put(val.Destination_Value__c,val.Destination_Value__c);
        }
        
       								 /*Cancellation Lost Data  */
        List<Mapping_Master__c> canLostData=[
            SELECT ID,Destination_Value__c, Source_OpCo__c,Destination_Field__c,Object__c 
            From Mapping_Master__c
            Where Destination_Field__c ='Cancellation_Lost_Data__c' and Object__c ='Opportunity'
        ];
        Map<String,String> canLostDataMap=new Map<String,String>();
        for(Mapping_Master__c val:canLostData)
        {
            canLostDataMap.put(val.Destination_Value__c,val.Destination_Value__c);
        }
        
         // Status Role Picklist value for comparison 
        List<String>stagePickListValues=new List<String>();
        Schema.DescribeFieldResult stageFieldLabel = Opportunity.StageName.getDescribe();
        List<Schema.PicklistEntry> sN = stageFieldLabel.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : sN){
            stagePickListValues.add(pickListVal.getLabel());
        } 
        
          // Type Picklist value for comparison 
        List<String>typePickListValues=new List<String>();
        Schema.DescribeFieldResult typeFieldLabel = Opportunity.Type.getDescribe();
        List<Schema.PicklistEntry> tY = typeFieldLabel.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : tY)
        {
            typePickListValues.add(pickListVal.getLabel());
        }
        
         // Market Seg Picklist value for comparison 
        List<String>mktSegPickListValues=new List<String>();
        Schema.DescribeFieldResult mktSegFieldLabel = Opportunity.Market_Segment__c.getDescribe();
        List<Schema.PicklistEntry> mS = mktSegFieldLabel.getPicklistValues();
        for( Schema.PicklistEntry mktSeg : mS){
            mktSegPickListValues.add(mktSeg.getLabel());
        }
        
        											/*Main Code Starts Opportunity Loop*/
         for(Opportunity opp:lstOpp)
        {
            if(opp.Skip_Trigger__c == true || opp.Source_OpCo_Record_Id__c==null || opp.Source_OpCo_Record_Id__c=='')
                continue;
            
            Map<String,List<String>> mapValues=new Map<String,List<String>>();
            // Condition to be removed 
            if(opp.LSIG_Contact__c==null)
            {
                opp.LSIG_Contact__c=lstRelContacts[0].LSIG_Contact__c; 
                opp.OpCo_Related_Contact__c=lstRelContacts[0].ID;
            }
            
             if(opp.OpCo_Line_Of_Business__c!=null)
            {
                if(opp.OpCo_Line_Of_Business__c.contains(','))
                {
                    List<String> value=opp.OpCo_Line_Of_Business__c.split(',');
                    mapValues.put('OpCo_Line_Of_Business__c',value);
                } 
                else
                {
                    List<String> value=new List<String>();
                    value.add(opp.OpCo_Line_Of_Business__c);
                    mapValues.put('OpCo_Line_Of_Business__c',value);
                }
            }
            
              if(opp.opCo_Market_Segment__c!=null)
            {
                if(opp.opCo_Market_Segment__c.contains(','))
                {
                    List<String> value=opp.opCo_Market_Segment__c.split(',');
                    mapValues.put('opCo_Market_Segment__c',value);
                } 
                else
                {
                    List<String> value=new List<String>();
                    value.add(opp.opCo_Market_Segment__c);
                    mapValues.put('opCo_Market_Segment__c',value);
                }
            }
            
              if(opp.OpCo_Product_Family__c!=null)
            {
                if(opp.OpCo_Product_Family__c.contains(','))
                {
                    List<String> value=opp.OpCo_Product_Family__c.split(',');
                    mapValues.put('OpCo_Product_Family__c',value);
                } 
                else
                {
                    List<String> value=new List<String>();
                    value.add(opp.OpCo_Product_Family__c);
                    mapValues.put('OpCo_Product_Family__c',value);
                }
            }
            
              if(opp.OpCo_Competitor_Data__c!=null)
            {
                if(opp.OpCo_Product_Family__c.contains(','))
                {
                    List<String> value=opp.OpCo_Competitor_Data__c.split(',');
                    mapValues.put('OpCo_Competitor_Data__c',value);
                } 
                else
                {
                    List<String> value=new List<String>();
                    value.add(opp.OpCo_Competitor_Data__c);
                    mapValues.put('OpCo_Competitor_Data__c',value);
                }
            }
            
            system.debug(mapValues);
           		             /*    OpCO Line Business      */
                List<String> values=mapValues.get('OpCo_Line_Of_Business__c');
                for(String val:values)
                {
                   for(Mapping_Master__c mapRes:mappingRec)
            		{
                         if(val==mapRes.Source_Value__c && opp.Source__c==mapRes.Source_OpCo__c && mapRes.Destination_Field__c=='Line_of_Business__c' )
               			 {
                   				Integer index=values.indexOf(val);
                             	values.set(index,mapRes.Destination_Value__c); 
                		 }  
                    }
                }
                mapValues.put('OpCo_Line_Of_Business__c',values);
                         /* End of OpCo Line Business */
            			 /*OpCo_Product_Family__c */
             List<String> prFam=mapValues.get('OpCo_Product_Family__c');
                for(String val:prFam)
                {
                   for(Mapping_Master__c mapRes:mappingRec)
            		{
                         if(val==mapRes.Source_Value__c && opp.Source__c==mapRes.Source_OpCo__c && mapRes.Destination_Field__c=='Line_of_Business__c' )
               			 {
                   				Integer index=prFam.indexOf(val);
                             	prFam.set(index,mapRes.Destination_Value__c); 
                		 }  
                    }
                    if(!prodFamilyMap.containskey(val) )
                		{
                  		        Integer index=prFam.indexOf(val);
                             	prFam.set(index,'Undefined');      
                		}
                }
            mapValues.put('OpCo_Product_Family__c',prFam);
            /*End of OpCo_Product_Family__c*/
            	system.debug(mapValues);
           
            /*End of Opportunity For Loop */
        }
        
    }
    
}