unpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>OpCo_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OpCo Account</label>
        <referenceTo>OpCo_Account__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source OpCo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beckman</fullName>
                </value>
                <value>
                    <fullName>IDBS</fullName>
                </value>
                <value>
                    <fullName>Leica</fullName>
                </value>
                <value>
                    <fullName>Moldev</fullName>
                </value>
                <value>
                    <fullName>SCIEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/OpCo_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>OpCo Accounts Data</relationshipLabel>
        <relationshipName>OpCo_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OpCo_Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OpCo Related Contact</label>
        <referenceTo>OpCo_Related_Contact__c</referenceTo>
        <relationshipLabel>OpCo Accounts Data</relationshipLabel>
        <relationshipName>OpCo_Accounts_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source OpCo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beckman</fullName>
                </value>
                <value>
                    <fullName>IDBS</fullName>
                </value>
                <value>
                    <fullName>Leica</fullName>
                </value>
                <value>
                    <fullName>Moldev</fullName>
                </value>
                <value>
                    <fullName>SCIEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OpCo Account Data</label>
    <nameField>
        <displayFormat>ID-{0000000}</displayFormat>
        <label>OpCo Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpCo Accounts Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/OpCo_Related_Contact__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>LSIG_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LSIG Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>OpCo Related Contacts</relationshipLabel>
        <relationshipName>OpCo_Related_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source OpCo Account</label>
        <referenceTo>OpCo_Account__c</referenceTo>
        <relationshipLabel>OpCo Related Contacts</relationshipLabel>
        <relationshipName>OpCo_Related_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source OpCo</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Beckman</fullName>
                </value>
                <value>
                    <fullName>IDBS</fullName>
                </value>
                <value>
                    <fullName>Leica</fullName>
                </value>
                <value>
                    <fullName>Moldev</fullName>
                </value>
                <value>
                    <fullName>SCIEX</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>OpCo Related Contact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpCo Related Contact</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact_Exists_in_OpCo__c</fullName>
        <label>Contact Exists in OpCo?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <label>Destination OpCo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Beckman</fullName>
                </value>
                <value>
                    <fullName>IDBS</fullName>
                </value>
                <value>
                    <fullName>Leica</fullName>
                </value>
                <value>
                    <fullName>Moldev</fullName>
                </value>
                <value>
                    <fullName>SCIEX</fullName>
                </value>
                <value>
                    <fullName>LSIG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interface_Status__c</fullName>
        <inlineHelpText>This would auto update after LSIG Contact selection &amp; backend process performs Sync with OpCo.</inlineHelpText>
        <label>Interface Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2-Awaiting</fullName>
                    <label>Awaiting OpCo Account/Contact Selection</label>
                </value>
                <value>
                    <fullName>3-Ready</fullName>
                    <label>Ready To Send To OpCo</label>
                </value>
                <value>
                    <fullName>4-Intransit</fullName>
                    <label>In-Transit To OpCo</label>
                </value>
                <value>
                    <fullName>5-Sent</fullName>
                    <label>In-Transit</label>
                </value>
                <value>
                    <fullName>6-Error</fullName>
                    <label>Failure in Transfer or Sync</label>
                </value>
                <value>
                    <fullName>7-Sync</fullName>
                    <label>Under Bi-Directional Sync</label>
                </value>
                <value>
                    <fullName>1-Awaiting</fullName>
                    <isActive>false</isActive>
                    <label>Awaiting LSIG Contact Selection</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LSIG_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LSIG Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpCo_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OpCo Account</label>
        <referenceTo>OpCo_Account__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OpCo_Related_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OpCo Related Contact</label>
        <referenceTo>OpCo_Related_Contact__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source OpCo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Beckman</fullName>
                </value>
                <value>
                    <fullName>IDBS</fullName>
                </value>
                <value>
                    <fullName>Leica</fullName>
                </value>
                <value>
                    <fullName>Moldev</fullName>
                </value>
                <value>
                    <fullName>SCIEX</fullName>
                </value>
                <value>
                    <fullName>LSIG</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Moldev</fullName>
        <active>true</active>
        <businessProcess>LSIG to OpCos Oppty</businessProcess>
        <description>Moldev Opportunities (Source &amp; LSIG)</description>
        <label>Moldev</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/classes/checkIfContactExistsNowInOpCoTest.cls
@isTest
public class checkIfContactExistsNowInOpCoTest {
    
    @isTest public static void checkTest(){
        
        Account acc= new Account();
        acc.Name='Pfizer Inc.';
        insert acc;
        
        
        contact con = new contact();
        con.LastName=acc.Name;
        con.Email='testmd1@g.com';
        con.AccountId=acc.Id;
        insert con;
        
        OpCo_Related_Contact__c opRelated = new OpCo_Related_Contact__c();
        opRelated.Name=con.Name;
        opRelated.Email__c='testmd1@g.com';
        opRelated.LSIG_Contact__c=con.Id;
        opRelated.Source__c='Moldev';        
      //  opRelated.Source_Account__c=acc.Id;
        insert opRelated;
        
        OpCo_Related_Contact__c opRelated1 = new OpCo_Related_Contact__c();
        opRelated1.Name=con.Name;
        opRelated1.Email__c='testmd1@g.com';
        opRelated1.LSIG_Contact__c=con.Id;
        opRelated1.Source__c='Moldev';        
        insert opRelated1;
          
        
        OpCo_Account__c opco=new OpCo_Account__c();
        opco.OpCo_Related_Contact__c=opRelated.id;
        opco.Source__c='Moldev';
        opco.Account__c=acc.id;
        insert opco;
       
        
        
        Opportunity op =new Opportunity();
        op.Name='Test # opp';
        op.StageName='Qualification';
        op.CloseDate=Date.valueOf('2023-11-28');
        op.Destination__c='Moldev'; 
        op.Interface_Status__c='2-Awaiting';
        op.LSIG_Contact__c=con.Id;        
        op.Contact_Exists_in_OpCo__c='No';
        op.OpCo_Related_Contact__c = opRelated.id;
        insert op;        
        update op;
        
         Opportunity op1 =new Opportunity();
        op1.Name='Test # opp';
        op1.StageName='Qualification';
        op1.CloseDate=Date.valueOf('2023-11-28');
        op1.Destination__c='Moldev'; 
        op1.Interface_Status__c='2-Awaiting';
        op1.LSIG_Contact__c=con.Id;        
        op1.Contact_Exists_in_OpCo__c='No';
        op1.OpCo_Related_Contact__c = opRelated.id;
        insert op1;  
        
        Test.startTest();
        checkIfContactExistsNowInOpCo umg=new checkIfContactExistsNowInOpCo();
        Database.executeBatch(umg);
        Test.stopTest();
        
        
    }
    
}